# build stage
FROM registry.fedoraproject.org/fedora:43 AS builder

# rocm 7.2.3 repo
RUN <<EOF
tee /etc/yum.repos.d/rocm.repo <<REPO
[ROCm-7.2.3]
name=ROCm7.2.3
baseurl=https://repo.radeon.com/rocm/rhel10/7.2.3/main
enabled=1
priority=50
gpgcheck=1
gpgkey=https://repo.radeon.com/rocm/rocm.gpg.key
REPO
EOF

# we want to keep ALL dnf downloaded packages in dnf cache,
# this is not the default, hackily add it to the config,
# assume there is not much in it. should be improved
RUN echo 'keepcache=True' >> /etc/dnf/dnf.conf

# deps
RUN --mount=type=cache,target=/var/cache/libdnf5 \
  dnf -y --nodocs --setopt=install_weak_deps=False \
  --exclude='*sdk*' --exclude='*samples*' --exclude='*-doc*' --exclude='*-docs*' \
  install \
  make gcc cmake lld clang clang-devel compiler-rt libcurl-devel ninja-build \
  rocm-llvm rocm-device-libs hip-runtime-amd hip-devel \
  rocblas rocblas-devel hipblas hipblas-devel rocm-cmake libomp-devel libomp \
  rocminfo radeontop \
  git-core vim sudo rsync patch

# rocm env
ENV ROCM_PATH=/opt/rocm \
  HIP_PATH=/opt/rocm \
  HIP_CLANG_PATH=/opt/rocm/llvm/bin \
  HIP_DEVICE_LIB_PATH=/opt/rocm/amdgcn/bitcode \
  PATH=/opt/rocm/bin:/opt/rocm/llvm/bin:$PATH

# llama.cpp
ARG REPO=https://github.com/ggerganov/llama.cpp.git
ARG BRANCH=master
# RUN --mount=type=cache,target=/opt/llama.cpp \
#   test -d .git || git clone -b ${BRANCH} --single-branch --recursive ${REPO} .



# build
COPY llama-grammar.patch /tmp/llama-grammar.patch
ADD --link ${REPO}#${BRANCH} /opt/llama.cpp
WORKDIR /opt/llama.cpp
RUN --mount=type=cache,target=/opt/llama.cpp/build \
 patch -p1 < /tmp/llama-grammar.patch \
  && cmake -S . -B build \
  -DGGML_HIP=ON \
  -DCMAKE_HIP_FLAGS="--rocm-path=/opt/rocm -mllvm --amdgpu-unroll-threshold-local=600" \
  -DAMDGPU_TARGETS=gfx1151 \
  -DCMAKE_BUILD_TYPE=Release \
  -DGGML_RPC=ON \
  -DLLAMA_HIP_UMA=ON \
  -DGGML_CUDA_ENABLE_UNIFIED_MEMORY=ON \
  -DROCM_PATH=/opt/rocm \
  -DHIP_PATH=/opt/rocm \
  -DHIP_PLATFORM=amd \
  && cmake --build build --config Release -- -j$(nproc) \
  && cmake --install build --config Release

# libs
RUN --mount=type=cache,target=/opt/llama.cpp/build \
  mkdir -p /usr/local/lib64 \
  && find /opt/llama.cpp/build -type f -name 'lib*.so*' -exec cp {} /usr/local/lib64/ \; \
  && ldconfig

# helper
COPY --link gguf-vram-estimator.py /usr/local/bin/gguf-vram-estimator.py
RUN chmod +x /usr/local/bin/gguf-vram-estimator.py

# runtime stage
FROM registry.fedoraproject.org/fedora-minimal:43 AS runtime
RUN echo 'keepcache=True' >> /etc/dnf/dnf.conf

# rocm 7.2.3 repo
RUN <<'EOF'
tee /etc/yum.repos.d/rocm.repo <<REPO
[ROCm-7.2.3]
name=ROCm7.2.3
baseurl=https://repo.radeon.com/rocm/rhel10/7.2.3/main
enabled=1
priority=50
gpgcheck=1
gpgkey=https://repo.radeon.com/rocm/rocm.gpg.key
REPO
EOF

# runtime deps
RUN --mount=type=cache,target=/var/cache/libdnf5 \
  microdnf -y --nodocs --setopt=install_weak_deps=0 \
  --exclude='*sdk*' --exclude='*samples*' --exclude='*-doc*' --exclude='*-docs*' \
  install \
  bash ca-certificates libatomic libstdc++ libgcc libgomp sudo \
  hip-runtime-amd rocblas hipblas \
  rocminfo radeontop procps-ng

# copy
COPY --from=builder /usr/local/ /usr/local/

# ld
RUN echo "/usr/local/lib"  > /etc/ld.so.conf.d/local.conf \
  && echo "/usr/local/lib64" >> /etc/ld.so.conf.d/local.conf \
  && ldconfig \
  && cp -n /usr/local/lib/libllama*.so* /usr/lib64/ 2>/dev/null || true \
  && cp -n /usr/local/lib64/libllama*.so* /usr/lib64/ 2>/dev/null || true \
  && ldconfig

# helper
COPY gguf-vram-estimator.py /usr/local/bin/gguf-vram-estimator.py
RUN chmod +x /usr/local/bin/gguf-vram-estimator.py

# profile
RUN printf '%s\n' \
  > /etc/profile.d/rocm.sh && chmod +x /etc/profile.d/rocm.sh \
  && echo 'source /etc/profile.d/rocm.sh' >> /etc/bashrc

# shell
CMD ["/bin/bash"]
